version: '3.8'

services:
  nse-fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nse_market_api
    ports:
      - "8000:8000"
    restart: always
    environment:
      - TZ=Asia/Kolkata
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
